// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/diary_entry.dart';
import 'data/models/quote.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 2129283912504731308),
      name: 'DiaryEntry',
      lastPropertyId: const obx_int.IdUid(10, 7939515074887798747),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3815754705253629423),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 9056707834929717653),
            name: 'date',
            type: 10,
            flags: 8,
            indexId: const obx_int.IdUid(1, 1737206013969646168)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 634288513383515268),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 603727512594350035),
            name: 'updatedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3365101524441325719),
            name: 'moodLabel',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1132853384983989860),
            name: 'specificEmoji',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 6698058745654112299),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 3335592737850718455),
            name: 'content',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 5677279471159351434),
            name: 'images',
            type: 30,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 7939515074887798747),
            name: 'cachedQuoteContent',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 1067589770953631987),
      name: 'Quote',
      lastPropertyId: const obx_int.IdUid(5, 8505436670919648811),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7765268502885458),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5826635064836403054),
            name: 'category',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(2, 6774069392427766861)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6090555629558749583),
            name: 'content',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7568174623838166178),
            name: 'author',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8505436670919648811),
            name: 'sourceId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(3, 2248850157426865772),
            relationTarget: 'QuoteSource')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 6019832415675060129),
      name: 'QuoteSource',
      lastPropertyId: const obx_int.IdUid(4, 3968443603496709949),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7319657625252599134),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7950215950425717328),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8499796918892357650),
            name: 'isEnabled',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3968443603496709949),
            name: 'importedAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'quotes', srcEntity: 'Quote', srcField: 'source')
      ])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(3, 6019832415675060129),
      lastIndexId: const obx_int.IdUid(3, 2248850157426865772),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    DiaryEntry: obx_int.EntityDefinition<DiaryEntry>(
        model: _entities[0],
        toOneRelations: (DiaryEntry object) => [],
        toManyRelations: (DiaryEntry object) => {},
        getId: (DiaryEntry object) => object.id,
        setId: (DiaryEntry object, int id) {
          object.id = id;
        },
        objectToFB: (DiaryEntry object, fb.Builder fbb) {
          final moodLabelOffset = fbb.writeString(object.moodLabel);
          final specificEmojiOffset = fbb.writeString(object.specificEmoji);
          final titleOffset =
              object.title == null ? null : fbb.writeString(object.title!);
          final contentOffset = fbb.writeString(object.content);
          final imagesOffset = object.images == null
              ? null
              : fbb.writeList(
                  object.images!.map(fbb.writeString).toList(growable: false));
          final cachedQuoteContentOffset = object.cachedQuoteContent == null
              ? null
              : fbb.writeString(object.cachedQuoteContent!);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.date.millisecondsSinceEpoch);
          fbb.addInt64(2, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(3, object.updatedAt.millisecondsSinceEpoch);
          fbb.addOffset(4, moodLabelOffset);
          fbb.addOffset(5, specificEmojiOffset);
          fbb.addOffset(6, titleOffset);
          fbb.addOffset(7, contentOffset);
          fbb.addOffset(8, imagesOffset);
          fbb.addOffset(9, cachedQuoteContentOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = DiaryEntry()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..date = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0))
            ..createdAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0))
            ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0))
            ..moodLabel = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..specificEmoji = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 14, '')
            ..title = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 16)
            ..content = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 18, '')
            ..images = const fb.ListReader<String>(
                    fb.StringReader(asciiOptimization: true),
                    lazy: false)
                .vTableGetNullable(buffer, rootOffset, 20)
            ..cachedQuoteContent =
                const fb.StringReader(asciiOptimization: true)
                    .vTableGetNullable(buffer, rootOffset, 22);

          return object;
        }),
    Quote: obx_int.EntityDefinition<Quote>(
        model: _entities[1],
        toOneRelations: (Quote object) => [object.source],
        toManyRelations: (Quote object) => {},
        getId: (Quote object) => object.id,
        setId: (Quote object, int id) {
          object.id = id;
        },
        objectToFB: (Quote object, fb.Builder fbb) {
          final categoryOffset = fbb.writeString(object.category);
          final contentOffset = fbb.writeString(object.content);
          final authorOffset =
              object.author == null ? null : fbb.writeString(object.author!);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, categoryOffset);
          fbb.addOffset(2, contentOffset);
          fbb.addOffset(3, authorOffset);
          fbb.addInt64(4, object.source.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final contentParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final categoryParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final authorParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final object = Quote(
              content: contentParam,
              category: categoryParam,
              author: authorParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.source.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.source.attach(store);
          return object;
        }),
    QuoteSource: obx_int.EntityDefinition<QuoteSource>(
        model: _entities[2],
        toOneRelations: (QuoteSource object) => [],
        toManyRelations: (QuoteSource object) => {
              obx_int.RelInfo<Quote>.toOneBacklink(
                      5, object.id, (Quote srcObject) => srcObject.source):
                  object.quotes
            },
        getId: (QuoteSource object) => object.id,
        setId: (QuoteSource object, int id) {
          object.id = id;
        },
        objectToFB: (QuoteSource object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addBool(2, object.isEnabled);
          fbb.addInt64(3, object.importedAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final isEnabledParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 8, false);
          final importedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0));
          final object = QuoteSource(
              name: nameParam,
              isEnabled: isEnabledParam,
              importedAt: importedAtParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          obx_int.InternalToManyAccess.setRelInfo<QuoteSource>(
              object.quotes,
              store,
              obx_int.RelInfo<Quote>.toOneBacklink(
                  5, object.id, (Quote srcObject) => srcObject.source));
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [DiaryEntry] entity fields to define ObjectBox queries.
class DiaryEntry_ {
  /// see [DiaryEntry.id]
  static final id =
      obx.QueryIntegerProperty<DiaryEntry>(_entities[0].properties[0]);

  /// see [DiaryEntry.date]
  static final date =
      obx.QueryDateProperty<DiaryEntry>(_entities[0].properties[1]);

  /// see [DiaryEntry.createdAt]
  static final createdAt =
      obx.QueryDateProperty<DiaryEntry>(_entities[0].properties[2]);

  /// see [DiaryEntry.updatedAt]
  static final updatedAt =
      obx.QueryDateProperty<DiaryEntry>(_entities[0].properties[3]);

  /// see [DiaryEntry.moodLabel]
  static final moodLabel =
      obx.QueryStringProperty<DiaryEntry>(_entities[0].properties[4]);

  /// see [DiaryEntry.specificEmoji]
  static final specificEmoji =
      obx.QueryStringProperty<DiaryEntry>(_entities[0].properties[5]);

  /// see [DiaryEntry.title]
  static final title =
      obx.QueryStringProperty<DiaryEntry>(_entities[0].properties[6]);

  /// see [DiaryEntry.content]
  static final content =
      obx.QueryStringProperty<DiaryEntry>(_entities[0].properties[7]);

  /// see [DiaryEntry.images]
  static final images =
      obx.QueryStringVectorProperty<DiaryEntry>(_entities[0].properties[8]);

  /// see [DiaryEntry.cachedQuoteContent]
  static final cachedQuoteContent =
      obx.QueryStringProperty<DiaryEntry>(_entities[0].properties[9]);
}

/// [Quote] entity fields to define ObjectBox queries.
class Quote_ {
  /// see [Quote.id]
  static final id = obx.QueryIntegerProperty<Quote>(_entities[1].properties[0]);

  /// see [Quote.category]
  static final category =
      obx.QueryStringProperty<Quote>(_entities[1].properties[1]);

  /// see [Quote.content]
  static final content =
      obx.QueryStringProperty<Quote>(_entities[1].properties[2]);

  /// see [Quote.author]
  static final author =
      obx.QueryStringProperty<Quote>(_entities[1].properties[3]);

  /// see [Quote.source]
  static final source =
      obx.QueryRelationToOne<Quote, QuoteSource>(_entities[1].properties[4]);
}

/// [QuoteSource] entity fields to define ObjectBox queries.
class QuoteSource_ {
  /// see [QuoteSource.id]
  static final id =
      obx.QueryIntegerProperty<QuoteSource>(_entities[2].properties[0]);

  /// see [QuoteSource.name]
  static final name =
      obx.QueryStringProperty<QuoteSource>(_entities[2].properties[1]);

  /// see [QuoteSource.isEnabled]
  static final isEnabled =
      obx.QueryBooleanProperty<QuoteSource>(_entities[2].properties[2]);

  /// see [QuoteSource.importedAt]
  static final importedAt =
      obx.QueryDateProperty<QuoteSource>(_entities[2].properties[3]);

  /// see [QuoteSource.quotes]
  static final quotes =
      obx.QueryBacklinkToMany<Quote, QuoteSource>(Quote_.source);
}
